version: '3.4'

services:
  pifagor-table:
    container_name: 'pifagor-table'
    build: .
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/angela-numerolog.ru:/etc/letsencrypt/live/angela-numerolog.ru
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
