version: '3.4'

services:
  pifagor-table:
    container_name: 'pifagor-table'
    build: .
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/certbot/conf/:/etc/nginx/ssl/
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443

  certbot:
    container_name: 'certbot'
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email dzeboevy@mail.ru --agree-tos --no-eff-email -d angela-numerolog.ru
    volumes:
      - ./nginx/certbot/conf/:/etc/letsencrypt
      - ./nginx/certbot/logs/:/var/log/letsencrypt
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt